version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
        - "8001:80"
        volumes:
        - "./nginx/config:/etc/nginx/conf.d"
        - "./nginx/www/:/var/www"
        links:
            - php-fpm

    php-fpm:
        image: php:7-fpm
        container_name: php-fpm
        volumes: 
        - "./nginx/www/:/var/www"